/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { _IncludesArea } from './models/_IncludesArea';
export type { _IncludesClusterMetroLine } from './models/_IncludesClusterMetroLine';
export type { _IncludesClusterMetroStation } from './models/_IncludesClusterMetroStation';
export type { _IncludesContact } from './models/_IncludesContact';
export type { _IncludesContactEmailValue } from './models/_IncludesContactEmailValue';
export type { _IncludesContactPhoneValue } from './models/_IncludesContactPhoneValue';
export type { _IncludesContactProperties } from './models/_IncludesContactProperties';
export type { _IncludesCountUrl } from './models/_IncludesCountUrl';
export type { _IncludesEducationalInstitutionItem } from './models/_IncludesEducationalInstitutionItem';
export type { _IncludesEducationLevel } from './models/_IncludesEducationLevel';
export type { _IncludesEmployerApplicantServices } from './models/_IncludesEmployerApplicantServices';
export type { _IncludesEmployerApplicantServicesObject } from './models/_IncludesEmployerApplicantServicesObject';
export type { _IncludesId } from './models/_IncludesId';
export type { _IncludesIdName } from './models/_IncludesIdName';
export type { _IncludesIdNameDesc } from './models/_IncludesIdNameDesc';
export type { _IncludesIdNameLastChangeTime } from './models/_IncludesIdNameLastChangeTime';
export type { _IncludesIdNameUid } from './models/_IncludesIdNameUid';
export type { _IncludesIdNameUrl } from './models/_IncludesIdNameUrl';
export type { _IncludesLanguageLevel } from './models/_IncludesLanguageLevel';
export type { _IncludesLanguageProperties } from './models/_IncludesLanguageProperties';
export type { _IncludesLinks } from './models/_IncludesLinks';
export type { _IncludesLogoUrls } from './models/_IncludesLogoUrls';
export type { _IncludesLogoUrls90 } from './models/_IncludesLogoUrls90';
export type { _IncludesMetroStation } from './models/_IncludesMetroStation';
export type { _IncludesName } from './models/_IncludesName';
export type { _IncludesNameDescription } from './models/_IncludesNameDescription';
export type { _IncludesNullableObject } from './models/_IncludesNullableObject';
export type { _IncludesNumericId } from './models/_IncludesNumericId';
export type { _IncludesPagination } from './models/_IncludesPagination';
export type { _IncludesSkillSetItem } from './models/_IncludesSkillSetItem';
export type { _IncludesSortingType } from './models/_IncludesSortingType';
export type { _IncludesThemeIcons } from './models/_IncludesThemeIcons';
export type { _IncludesUrl } from './models/_IncludesUrl';
export type { ApplicantCommentsAccessType } from './models/ApplicantCommentsAccessType';
export type { ApplicantCommentsApplicantCommentItem } from './models/ApplicantCommentsApplicantCommentItem';
export type { ApplicantCommentsApplicantCommentItems } from './models/ApplicantCommentsApplicantCommentItems';
export type { ApplicantCommentsApplicantCommentsList } from './models/ApplicantCommentsApplicantCommentsList';
export type { ApplicantCommentsAuthor } from './models/ApplicantCommentsAuthor';
export type { ArtifactsArtifactConditions } from './models/ArtifactsArtifactConditions';
export type { ArtifactsArtifactItem } from './models/ArtifactsArtifactItem';
export type { ArtifactsArtifactPhotoItems } from './models/ArtifactsArtifactPhotoItems';
export type { ArtifactsArtifactPhotoResponse } from './models/ArtifactsArtifactPhotoResponse';
export type { ArtifactsArtifactPortfolioItem } from './models/ArtifactsArtifactPortfolioItem';
export type { ArtifactsArtifactPortfolioItems } from './models/ArtifactsArtifactPortfolioItems';
export type { ArtifactsArtifactPortfolioResponse } from './models/ArtifactsArtifactPortfolioResponse';
export type { ArtifactsArtifactUploadBody } from './models/ArtifactsArtifactUploadBody';
export type { ArtifactsCounters } from './models/ArtifactsCounters';
export type { ArtifactsDescription } from './models/ArtifactsDescription';
export type { ArtifactsFields } from './models/ArtifactsFields';
export type { ArtifactsFile } from './models/ArtifactsFile';
export type { ArtifactsPortfolioDescription } from './models/ArtifactsPortfolioDescription';
export { ArtifactsState } from './models/ArtifactsState';
export type { ArtifactsType } from './models/ArtifactsType';
export { AuthAppToken } from './models/AuthAppToken';
export { AuthClientCredentials } from './models/AuthClientCredentials';
export { AuthCode } from './models/AuthCode';
export { AuthRefreshToken } from './models/AuthRefreshToken';
export { AuthUserToken } from './models/AuthUserToken';
export type { AuthUserTokenAndAppToken } from './models/AuthUserTokenAndAppToken';
export type { ClickmeStatisticsItem } from './models/ClickmeStatisticsItem';
export type { ClickmeStatisticsResponse } from './models/ClickmeStatisticsResponse';
export type { CredsAnswers } from './models/CredsAnswers';
export type { CredsCreds } from './models/CredsCreds';
export type { CredsCredsUpdate } from './models/CredsCredsUpdate';
export type { CredsQuestions } from './models/CredsQuestions';
export type { CredsResumeCreds } from './models/CredsResumeCreds';
export type { DictionariesAreaCommon } from './models/DictionariesAreaCommon';
export type { DictionariesAreaItem } from './models/DictionariesAreaItem';
export type { DictionariesAreaResponse } from './models/DictionariesAreaResponse';
export type { DictionariesBranchItem } from './models/DictionariesBranchItem';
export type { DictionariesCountriesResponse } from './models/DictionariesCountriesResponse';
export type { DictionariesCurrencyItem } from './models/DictionariesCurrencyItem';
export type { DictionariesDictResponse } from './models/DictionariesDictResponse';
export type { DictionariesDistrictItem } from './models/DictionariesDistrictItem';
export type { DictionariesDistrictsResponse } from './models/DictionariesDistrictsResponse';
export type { DictionariesFacultiesResponse } from './models/DictionariesFacultiesResponse';
export type { DictionariesIndustriesResponse } from './models/DictionariesIndustriesResponse';
export type { DictionariesLangItem } from './models/DictionariesLangItem';
export type { DictionariesLangResponse } from './models/DictionariesLangResponse';
export type { DictionariesSalaryStatisticsAreaItem } from './models/DictionariesSalaryStatisticsAreaItem';
export type { DictionariesSalaryStatisticsAreaResponse } from './models/DictionariesSalaryStatisticsAreaResponse';
export type { DictionariesSalaryStatisticsEmployeeLevelResponse } from './models/DictionariesSalaryStatisticsEmployeeLevelResponse';
export type { DictionariesSalaryStatisticsProfessionalAreasResponse } from './models/DictionariesSalaryStatisticsProfessionalAreasResponse';
export type { DictionariesSalaryStatisticsSpecializations } from './models/DictionariesSalaryStatisticsSpecializations';
export type { DictionariesSkillsResponse } from './models/DictionariesSkillsResponse';
export type { EmployerAddressesEmployerAddressesResponse } from './models/EmployerAddressesEmployerAddressesResponse';
export type { EmployerAddressesEmployerAddressItem } from './models/EmployerAddressesEmployerAddressItem';
export type { EmployerAddressesEmployerAddressItemResponse } from './models/EmployerAddressesEmployerAddressItemResponse';
export type { EmployerAddressesEmployerAddressItems } from './models/EmployerAddressesEmployerAddressItems';
export type { EmployerDictionariesTestItem } from './models/EmployerDictionariesTestItem';
export type { EmployerDictionariesTestsResponse } from './models/EmployerDictionariesTestsResponse';
export type { EmployerManagersAddEmployerManager } from './models/EmployerManagersAddEmployerManager';
export type { EmployerManagersArea } from './models/EmployerManagersArea';
export type { EmployerManagersAreaId } from './models/EmployerManagersAreaId';
export type { EmployerManagersEmployerManagerId } from './models/EmployerManagersEmployerManagerId';
export type { EmployerManagersEmployerManagerInfo } from './models/EmployerManagersEmployerManagerInfo';
export type { EmployerManagersEmployerManagerItem } from './models/EmployerManagersEmployerManagerItem';
export type { EmployerManagersEmployerManagerLimits } from './models/EmployerManagersEmployerManagerLimits';
export type { EmployerManagersManagerData } from './models/EmployerManagersManagerData';
export type { EmployerManagersManagerType } from './models/EmployerManagersManagerType';
export type { EmployerManagersManagerTypeId } from './models/EmployerManagersManagerTypeId';
export type { EmployerManagersPermissions } from './models/EmployerManagersPermissions';
export type { EmployerManagersPhone } from './models/EmployerManagersPhone';
export type { EmployerManagersResponse } from './models/EmployerManagersResponse';
export type { EmployerManagersResumeView } from './models/EmployerManagersResumeView';
export type { EmployerManagerTypesAvailablePermissions } from './models/EmployerManagerTypesAvailablePermissions';
export type { EmployerManagerTypesEmployerManagerTypesItem } from './models/EmployerManagerTypesEmployerManagerTypesItem';
export type { EmployerManagerTypesResponse } from './models/EmployerManagerTypesResponse';
export { EmployersBrandingBrandingType } from './models/EmployersBrandingBrandingType';
export type { EmployersBrandingBrandParameters } from './models/EmployersBrandingBrandParameters';
export type { EmployersBrandingConstructor } from './models/EmployersBrandingConstructor';
export { EmployersBrandingConstructorGalleryWidget } from './models/EmployersBrandingConstructorGalleryWidget';
export type { EmployersBrandingConstructorHeaderPicture } from './models/EmployersBrandingConstructorHeaderPicture';
export type { EmployersBrandingEmployerBranding } from './models/EmployersBrandingEmployerBranding';
export type { EmployersBrandingEmployerBrandType } from './models/EmployersBrandingEmployerBrandType';
export type { EmployersBrandingMakeup } from './models/EmployersBrandingMakeup';
export type { EmployersEmployerDepartmentsResponse } from './models/EmployersEmployerDepartmentsResponse';
export type { EmployersEmployerInfo } from './models/EmployersEmployerInfo';
export type { EmployersEmployerInfoShort } from './models/EmployersEmployerInfoShort';
export type { EmployersEmployerItem } from './models/EmployersEmployerItem';
export type { EmployersEmployerItemShort } from './models/EmployersEmployerItemShort';
export type { EmployersEmployersBlacklisted } from './models/EmployersEmployersBlacklisted';
export type { EmployersEmployersBlacklistedItem } from './models/EmployersEmployersBlacklistedItem';
export type { EmployersEmployersBlacklistedResponse } from './models/EmployersEmployersBlacklistedResponse';
export type { EmployersEmployersList } from './models/EmployersEmployersList';
export type { EmployersEmployersState } from './models/EmployersEmployersState';
export type { EmployersEmployerVacancyAreasItems } from './models/EmployersEmployerVacancyAreasItems';
export type { EmployersEmployerVacancyAreasResponse } from './models/EmployersEmployerVacancyAreasResponse';
export type { EmployerServicesBalance } from './models/EmployerServicesBalance';
export type { EmployerServicesEmployerServiceItem } from './models/EmployerServicesEmployerServiceItem';
export type { EmployerServicesEmployerServices } from './models/EmployerServicesEmployerServices';
export type { EmployerServicesMethodAccess } from './models/EmployerServicesMethodAccess';
export type { EmployerServicesMethodAccessItem } from './models/EmployerServicesMethodAccessItem';
export type { EmployerServicesServiceType } from './models/EmployerServicesServiceType';
export type { EmployersFunnelStage } from './models/EmployersFunnelStage';
export type { EmployersFunnelSubstate } from './models/EmployersFunnelSubstate';
export type { EmployersInsiderInterviews } from './models/EmployersInsiderInterviews';
export type { EmployersVacancyBrandedTemplatesList } from './models/EmployersVacancyBrandedTemplatesList';
export type { ErrorsArtifactUploadBadJsonData } from './models/ErrorsArtifactUploadBadJsonData';
export { ErrorsArtifactUploadError } from './models/ErrorsArtifactUploadError';
export type { ErrorsArtifactUploadErrors } from './models/ErrorsArtifactUploadErrors';
export { ErrorsBadRequestPublishResumeError } from './models/ErrorsBadRequestPublishResumeError';
export type { ErrorsBadRequestPublishResumeErrors } from './models/ErrorsBadRequestPublishResumeErrors';
export { ErrorsCommonBadArgumentError } from './models/ErrorsCommonBadArgumentError';
export type { ErrorsCommonBadArgumentErrors } from './models/ErrorsCommonBadArgumentErrors';
export type { ErrorsCommonBadAuthCaptchaPrivate } from './models/ErrorsCommonBadAuthCaptchaPrivate';
export type { ErrorsCommonBadAuthorizationBadParameters } from './models/ErrorsCommonBadAuthorizationBadParameters';
export type { ErrorsCommonBadAuthorizationCommonAndEmployerError } from './models/ErrorsCommonBadAuthorizationCommonAndEmployerError';
export type { ErrorsCommonBadAuthorizationCommonAndPaymentMethodError } from './models/ErrorsCommonBadAuthorizationCommonAndPaymentMethodError';
export { ErrorsCommonBadAuthorizationEmployerError } from './models/ErrorsCommonBadAuthorizationEmployerError';
export { ErrorsCommonBadAuthorizationError } from './models/ErrorsCommonBadAuthorizationError';
export { ErrorsCommonBadAuthorizationErrors } from './models/ErrorsCommonBadAuthorizationErrors';
export { ErrorsCommonBadAuthorizationInvalidClientError } from './models/ErrorsCommonBadAuthorizationInvalidClientError';
export { ErrorsCommonBadAuthorizationInvalidGrantError } from './models/ErrorsCommonBadAuthorizationInvalidGrantError';
export { ErrorsCommonBadAuthorizationInvalidRequestError } from './models/ErrorsCommonBadAuthorizationInvalidRequestError';
export { ErrorsCommonBadAuthorizationPaymentMethodError } from './models/ErrorsCommonBadAuthorizationPaymentMethodError';
export type { ErrorsCommonBadAuthorizationPaymentMethodErrors } from './models/ErrorsCommonBadAuthorizationPaymentMethodErrors';
export { ErrorsCommonBadAuthorizationUnsupportedGrantTypeError } from './models/ErrorsCommonBadAuthorizationUnsupportedGrantTypeError';
export { ErrorsCommonBadJsonDataError } from './models/ErrorsCommonBadJsonDataError';
export type { ErrorsCommonBadJsonDataErrors } from './models/ErrorsCommonBadJsonDataErrors';
export type { ErrorsCommonBadRequestBadArgumentBadRequestAndBadArgumentErrors } from './models/ErrorsCommonBadRequestBadArgumentBadRequestAndBadArgumentErrors';
export { ErrorsCommonBadRequestError } from './models/ErrorsCommonBadRequestError';
export type { ErrorsCommonBadRequestErrors } from './models/ErrorsCommonBadRequestErrors';
export { ErrorsCommonCaptchaError } from './models/ErrorsCommonCaptchaError';
export type { ErrorsCommonCaptchaErrors } from './models/ErrorsCommonCaptchaErrors';
export { ErrorsCommonConflictBothChangedError } from './models/ErrorsCommonConflictBothChangedError';
export { ErrorsCommonConflictBothChangedErrors } from './models/ErrorsCommonConflictBothChangedErrors';
export type { ErrorsCommonErrorRequestId } from './models/ErrorsCommonErrorRequestId';
export { ErrorsCommonNotFoundError } from './models/ErrorsCommonNotFoundError';
export type { ErrorsCommonNotFoundErrors } from './models/ErrorsCommonNotFoundErrors';
export { ErrorsDictionariesBadArgumentError } from './models/ErrorsDictionariesBadArgumentError';
export type { ErrorsDictionariesBadArgumentErrors } from './models/ErrorsDictionariesBadArgumentErrors';
export { ErrorsDraftError } from './models/ErrorsDraftError';
export { ErrorsEmployerBlacklistedError } from './models/ErrorsEmployerBlacklistedError';
export type { ErrorsEmployerBlacklistedErrors } from './models/ErrorsEmployerBlacklistedErrors';
export { ErrorsEmployerBlacklistedNotFoundError } from './models/ErrorsEmployerBlacklistedNotFoundError';
export type { ErrorsEmployerBlacklistedNotFoundErrors } from './models/ErrorsEmployerBlacklistedNotFoundErrors';
export { ErrorsEmployerManagerBadArgumentError } from './models/ErrorsEmployerManagerBadArgumentError';
export type { ErrorsEmployerManagerBadArgumentErrors } from './models/ErrorsEmployerManagerBadArgumentErrors';
export { ErrorsEmployerManagerBadAuthorizationError } from './models/ErrorsEmployerManagerBadAuthorizationError';
export type { ErrorsEmployerManagerBadAuthorizationErrors } from './models/ErrorsEmployerManagerBadAuthorizationErrors';
export type { ErrorsEmployerManagerBadRequestAndBadArgumentErrors } from './models/ErrorsEmployerManagerBadRequestAndBadArgumentErrors';
export { ErrorsNegotiationEditMessageError } from './models/ErrorsNegotiationEditMessageError';
export type { ErrorsNegotiationEditMessageErrors } from './models/ErrorsNegotiationEditMessageErrors';
export type { ErrorsNegotiationEditMessageForbiddenErrors } from './models/ErrorsNegotiationEditMessageForbiddenErrors';
export type { ErrorsNegotiationForbiddenError } from './models/ErrorsNegotiationForbiddenError';
export { ErrorsNegotiationForbiddenErrors } from './models/ErrorsNegotiationForbiddenErrors';
export { ErrorsNegotiationHideResponseError } from './models/ErrorsNegotiationHideResponseError';
export type { ErrorsNegotiationHideResponseErrors } from './models/ErrorsNegotiationHideResponseErrors';
export type { ErrorsNegotiationHideResponseForbiddenErrors } from './models/ErrorsNegotiationHideResponseForbiddenErrors';
export type { ErrorsNegotiationHideResponseTooEarlyErrors } from './models/ErrorsNegotiationHideResponseTooEarlyErrors';
export type { ErrorsNegotiationNegotiationsBadAuthorizationErrors } from './models/ErrorsNegotiationNegotiationsBadAuthorizationErrors';
export type { ErrorsNegotiationNegotiationsNotFoundErrors } from './models/ErrorsNegotiationNegotiationsNotFoundErrors';
export { ErrorsNegotiationNotFoundError } from './models/ErrorsNegotiationNotFoundError';
export type { ErrorsNegotiationNotFoundErrors } from './models/ErrorsNegotiationNotFoundErrors';
export { ErrorsNegotiationTopicsStateChangeDeniedError } from './models/ErrorsNegotiationTopicsStateChangeDeniedError';
export { ErrorsRequestEntityTooLargeError } from './models/ErrorsRequestEntityTooLargeError';
export type { ErrorsRequestEntityTooLargeErrors } from './models/ErrorsRequestEntityTooLargeErrors';
export { ErrorsResumeAddEditConflictError } from './models/ErrorsResumeAddEditConflictError';
export type { ErrorsResumeAddEditConflictErrors } from './models/ErrorsResumeAddEditConflictErrors';
export { ErrorsResumeAddEditError } from './models/ErrorsResumeAddEditError';
export type { ErrorsResumeAddEditErrors } from './models/ErrorsResumeAddEditErrors';
export type { ErrorsResumeBadArgTooManyResumesErrors } from './models/ErrorsResumeBadArgTooManyResumesErrors';
export type { ErrorsResumeBadArgumentResumeErrors } from './models/ErrorsResumeBadArgumentResumeErrors';
export { ErrorsResumePhoneConfirmBadArgumentError } from './models/ErrorsResumePhoneConfirmBadArgumentError';
export type { ErrorsResumePhoneConfirmBadArgumentErrors } from './models/ErrorsResumePhoneConfirmBadArgumentErrors';
export { ErrorsResumePhoneConfirmForbiddenError } from './models/ErrorsResumePhoneConfirmForbiddenError';
export type { ErrorsResumePhoneConfirmForbiddenErrors } from './models/ErrorsResumePhoneConfirmForbiddenErrors';
export { ErrorsResumePhoneGenerateCodeBadArgumentError } from './models/ErrorsResumePhoneGenerateCodeBadArgumentError';
export type { ErrorsResumePhoneGenerateCodeBadArgumentErrors } from './models/ErrorsResumePhoneGenerateCodeBadArgumentErrors';
export { ErrorsResumePhoneGenerateCodeForbiddenError } from './models/ErrorsResumePhoneGenerateCodeForbiddenError';
export type { ErrorsResumePhoneGenerateCodeForbiddenErrors } from './models/ErrorsResumePhoneGenerateCodeForbiddenErrors';
export { ErrorsResumeTooManyRequestsApplicantError } from './models/ErrorsResumeTooManyRequestsApplicantError';
export type { ErrorsResumeTooManyRequestsApplicantErrors } from './models/ErrorsResumeTooManyRequestsApplicantErrors';
export { ErrorsResumeTooManyRequestsEmployerError } from './models/ErrorsResumeTooManyRequestsEmployerError';
export type { ErrorsResumeTooManyRequestsEmployerErrors } from './models/ErrorsResumeTooManyRequestsEmployerErrors';
export { ErrorsResumeTooManyResumesError } from './models/ErrorsResumeTooManyResumesError';
export type { ErrorsResumeTooManyResumesErrors } from './models/ErrorsResumeTooManyResumesErrors';
export { ErrorsResumeVisibilityError } from './models/ErrorsResumeVisibilityError';
export type { ErrorsResumeVisibilityErrors } from './models/ErrorsResumeVisibilityErrors';
export type { ErrorsResumeVisibilityErrorsBadRequest } from './models/ErrorsResumeVisibilityErrorsBadRequest';
export { ErrorsSavedSearchForbiddenError } from './models/ErrorsSavedSearchForbiddenError';
export type { ErrorsSavedSearchForbiddenErrors } from './models/ErrorsSavedSearchForbiddenErrors';
export { ErrorsSavedSearchNotFoundError } from './models/ErrorsSavedSearchNotFoundError';
export type { ErrorsSavedSearchNotFoundErrors } from './models/ErrorsSavedSearchNotFoundErrors';
export type { ErrorsVacancyAddEditBadAuthForbiddenErrors } from './models/ErrorsVacancyAddEditBadAuthForbiddenErrors';
export { ErrorsVacancyAddEditBadJsonDataError } from './models/ErrorsVacancyAddEditBadJsonDataError';
export type { ErrorsVacancyAddEditBadJsonDataErrors } from './models/ErrorsVacancyAddEditBadJsonDataErrors';
export type { ErrorsVacancyAddEditCombinedBadJsonDataErrors } from './models/ErrorsVacancyAddEditCombinedBadJsonDataErrors';
export { ErrorsVacancyAddEditForbiddenError } from './models/ErrorsVacancyAddEditForbiddenError';
export type { ErrorsVacancyAddEditForbiddenErrors } from './models/ErrorsVacancyAddEditForbiddenErrors';
export { ErrorsVacancyApplyBadRequestError } from './models/ErrorsVacancyApplyBadRequestError';
export { ErrorsVacancyApplyBadRequestErrors } from './models/ErrorsVacancyApplyBadRequestErrors';
export { ErrorsVacancyApplyForbiddenError } from './models/ErrorsVacancyApplyForbiddenError';
export { ErrorsVacancyApplyForbiddenErrors } from './models/ErrorsVacancyApplyForbiddenErrors';
export { ErrorsVacancyBlacklistedBadRequestError } from './models/ErrorsVacancyBlacklistedBadRequestError';
export type { ErrorsVacancyBlacklistedBadRequestErrors } from './models/ErrorsVacancyBlacklistedBadRequestErrors';
export { ErrorsVacancyBlacklistedNotFoundError } from './models/ErrorsVacancyBlacklistedNotFoundError';
export type { ErrorsVacancyBlacklistedNotFoundErrors } from './models/ErrorsVacancyBlacklistedNotFoundErrors';
export type { ErrorsVacancyError } from './models/ErrorsVacancyError';
export type { ErrorsVacancyErrors } from './models/ErrorsVacancyErrors';
export { ErrorsVacancyFavoritedBadAuthError } from './models/ErrorsVacancyFavoritedBadAuthError';
export type { ErrorsVacancyFavoritedBadAuthErrors } from './models/ErrorsVacancyFavoritedBadAuthErrors';
export type { ErrorsVacancyFavoritedCombinedBadAuthErrors } from './models/ErrorsVacancyFavoritedCombinedBadAuthErrors';
export { ErrorsVacancyProlongateError } from './models/ErrorsVacancyProlongateError';
export type { ErrorsVacancyProlongateErrors } from './models/ErrorsVacancyProlongateErrors';
export type { ErrorsVacancyProlongateForbidden } from './models/ErrorsVacancyProlongateForbidden';
export type { GeocoderAddress } from './models/GeocoderAddress';
export type { HHUserAgent } from './models/HHUserAgent';
export { Host } from './models/Host';
export type { Id } from './models/Id';
export type { Locale } from './models/Locale';
export type { LocalesLocaleItem } from './models/LocalesLocaleItem';
export type { LocalesLocales } from './models/LocalesLocales';
export type { LocalesResumeLocaleItem } from './models/LocalesResumeLocaleItem';
export type { LocalesResumeLocales } from './models/LocalesResumeLocales';
export type { MailTemplatesMailTemplate } from './models/MailTemplatesMailTemplate';
export type { MailTemplatesMailTemplateInput } from './models/MailTemplatesMailTemplateInput';
export type { MailTemplatesMailTemplates } from './models/MailTemplatesMailTemplates';
export type { ManagerAccount } from './models/ManagerAccount';
export type { ManagerAccountCompany } from './models/ManagerAccountCompany';
export type { ManagerAccounts } from './models/ManagerAccounts';
export type { ManagerSettings } from './models/ManagerSettings';
export type { ManagerSettingsCurrency } from './models/ManagerSettingsCurrency';
export type { MeAnyProfile } from './models/MeAnyProfile';
export type { MeAnyUserProfile } from './models/MeAnyUserProfile';
export type { MeApplicantProfile } from './models/MeApplicantProfile';
export type { MeApplicantProfileCounters } from './models/MeApplicantProfileCounters';
export type { MeChangeName } from './models/MeChangeName';
export type { MeCommonProfile } from './models/MeCommonProfile';
export type { MeEmployerProfile } from './models/MeEmployerProfile';
export type { MeEmployerProfileCompany } from './models/MeEmployerProfileCompany';
export type { MeEmployerProfileCompanyDeprecated } from './models/MeEmployerProfileCompanyDeprecated';
export type { MeEmployerProfileManager } from './models/MeEmployerProfileManager';
export type { MeEmployerProfilePersonalManager } from './models/MeEmployerProfilePersonalManager';
export type { MeManagerProfile } from './models/MeManagerProfile';
export type { MeProfile } from './models/MeProfile';
export type { MeSetInSearch } from './models/MeSetInSearch';
export type { MetroCityMetroItem } from './models/MetroCityMetroItem';
export type { MetroLineStation } from './models/MetroLineStation';
export type { MetroMetroItem } from './models/MetroMetroItem';
export type { MetroMetroLine } from './models/MetroMetroLine';
export type { MetroMetroLineWithStations } from './models/MetroMetroLineWithStations';
export type { MetroMetroResponse } from './models/MetroMetroResponse';
export type { NegotiationsAction } from './models/NegotiationsAction';
export type { NegotiationsApplicantNegotiation } from './models/NegotiationsApplicantNegotiation';
export type { NegotiationsApplicantNegotiationsResponse } from './models/NegotiationsApplicantNegotiationsResponse';
export type { NegotiationsAssessment } from './models/NegotiationsAssessment';
export type { NegotiationsAuthor } from './models/NegotiationsAuthor';
export type { NegotiationsCollectionNegotiations } from './models/NegotiationsCollectionNegotiations';
export type { NegotiationsCollectionNegotiationsResponse } from './models/NegotiationsCollectionNegotiationsResponse';
export type { NegotiationsEmployerNegotiation } from './models/NegotiationsEmployerNegotiation';
export type { NegotiationsListItem } from './models/NegotiationsListItem';
export type { NegotiationsListItems } from './models/NegotiationsListItems';
export type { NegotiationsListResponse } from './models/NegotiationsListResponse';
export type { NegotiationsMessage } from './models/NegotiationsMessage';
export type { NegotiationsMessageSent } from './models/NegotiationsMessageSent';
export type { NegotiationsMessagesGet } from './models/NegotiationsMessagesGet';
export type { NegotiationsMessagesGetResponse } from './models/NegotiationsMessagesGetResponse';
export type { NegotiationsNegotiationCommonFields } from './models/NegotiationsNegotiationCommonFields';
export type { NegotiationsNegotiationGetResponse } from './models/NegotiationsNegotiationGetResponse';
export type { NegotiationsNegotiationMessageTemplate } from './models/NegotiationsNegotiationMessageTemplate';
export type { NegotiationsNegotiationMessageTemplates } from './models/NegotiationsNegotiationMessageTemplates';
export type { NegotiationsNegotiationsCollection } from './models/NegotiationsNegotiationsCollection';
export type { NegotiationsNegotiationsCollections } from './models/NegotiationsNegotiationsCollections';
export type { NegotiationsNegotiationsOrderTypes } from './models/NegotiationsNegotiationsOrderTypes';
export type { NegotiationsNegotiationsStatistics } from './models/NegotiationsNegotiationsStatistics';
export type { NegotiationsNegotiationsStatisticsEmployerResponse } from './models/NegotiationsNegotiationsStatisticsEmployerResponse';
export type { NegotiationsNegotiationsStatisticsManagerResponse } from './models/NegotiationsNegotiationsStatisticsManagerResponse';
export type { NegotiationsNegotiationsSubCollection } from './models/NegotiationsNegotiationsSubCollection';
export { NegotiationsNegotiationTestResultsResponse } from './models/NegotiationsNegotiationTestResultsResponse';
export type { NegotiationsObjectsCounters } from './models/NegotiationsObjectsCounters';
export type { NegotiationsObjectsEmployerCounters } from './models/NegotiationsObjectsEmployerCounters';
export type { NegotiationsObjectsEmployerTopicResume } from './models/NegotiationsObjectsEmployerTopicResume';
export type { NegotiationsObjectsPoliteness } from './models/NegotiationsObjectsPoliteness';
export type { NegotiationsObjectsStates } from './models/NegotiationsObjectsStates';
export type { NegotiationsObjectsSubCollections } from './models/NegotiationsObjectsSubCollections';
export type { NegotiationsObjectsTopicItem } from './models/NegotiationsObjectsTopicItem';
export { NegotiationsObjectsTopicItemCommon } from './models/NegotiationsObjectsTopicItemCommon';
export type { NegotiationsObjectsTopicResume } from './models/NegotiationsObjectsTopicResume';
export type { NegotiationsPhoneCallItem } from './models/NegotiationsPhoneCallItem';
export type { NegotiationsPhoneCalls } from './models/NegotiationsPhoneCalls';
export type { ProfessionalRolesCatalog } from './models/ProfessionalRolesCatalog';
export type { ProfessionalRolesCategory } from './models/ProfessionalRolesCategory';
export type { ProfessionalRolesRole } from './models/ProfessionalRolesRole';
export type { ProfileFieldsAddressCoordinates } from './models/ProfileFieldsAddressCoordinates';
export type { ProfileFieldsArea } from './models/ProfileFieldsArea';
export type { ProfileFieldsCommunicationMethod } from './models/ProfileFieldsCommunicationMethod';
export type { ProfileFieldsDistrict } from './models/ProfileFieldsDistrict';
export type { ProfileFieldsEducation } from './models/ProfileFieldsEducation';
export type { ProfileFieldsEducationAdditional } from './models/ProfileFieldsEducationAdditional';
export type { ProfileFieldsEducationElementary } from './models/ProfileFieldsEducationElementary';
export type { ProfileFieldsEducationPrimary } from './models/ProfileFieldsEducationPrimary';
export type { ProfileFieldsEducationResumes } from './models/ProfileFieldsEducationResumes';
export type { ProfileFieldsEducationResumesItem } from './models/ProfileFieldsEducationResumesItem';
export type { ProfileFieldsOneOfEducation } from './models/ProfileFieldsOneOfEducation';
export type { ProfileFieldsOtherCommunicationMethod } from './models/ProfileFieldsOtherCommunicationMethod';
export type { ProfileFieldsPreferredWorkArea } from './models/ProfileFieldsPreferredWorkArea';
export type { ProfilePhoto } from './models/ProfilePhoto';
export type { ProfileProfileConditions } from './models/ProfileProfileConditions';
export type { ProfileProfileResumeConditions } from './models/ProfileProfileResumeConditions';
export type { ProfileProfileResumes } from './models/ProfileProfileResumes';
export type { ProfileProfileResumesListItemView } from './models/ProfileProfileResumesListItemView';
export type { ProfileProfileUpdate } from './models/ProfileProfileUpdate';
export type { ProfileProfileView } from './models/ProfileProfileView';
export type { ProfileVideosList } from './models/ProfileVideosList';
export type { ResumeAddResumeRequest } from './models/ResumeAddResumeRequest';
export type { ResumeApplicantFields } from './models/ResumeApplicantFields';
export type { ResumeEditResume } from './models/ResumeEditResume';
export type { ResumeEditResumeRequest } from './models/ResumeEditResumeRequest';
export type { ResumeEmployerFields } from './models/ResumeEmployerFields';
export type { ResumeNullableFields } from './models/ResumeNullableFields';
export type { ResumeObjectsAccess } from './models/ResumeObjectsAccess';
export type { ResumeObjectsActions } from './models/ResumeObjectsActions';
export type { ResumeObjectsActionsForOwner } from './models/ResumeObjectsActionsForOwner';
export type { ResumeObjectsArea } from './models/ResumeObjectsArea';
export type { ResumeObjectsAutoHideTime } from './models/ResumeObjectsAutoHideTime';
export type { ResumeObjectsCertificate } from './models/ResumeObjectsCertificate';
export type { ResumeObjectsContact } from './models/ResumeObjectsContact';
export type { ResumeObjectsCounters } from './models/ResumeObjectsCounters';
export type { ResumeObjectsDownload } from './models/ResumeObjectsDownload';
export type { ResumeObjectsDownloadPdfRtf } from './models/ResumeObjectsDownloadPdfRtf';
export type { ResumeObjectsDriverLicenseTypes } from './models/ResumeObjectsDriverLicenseTypes';
export type { ResumeObjectsEducation } from './models/ResumeObjectsEducation';
export type { ResumeObjectsEducationAdditional } from './models/ResumeObjectsEducationAdditional';
export type { ResumeObjectsEducationElementary } from './models/ResumeObjectsEducationElementary';
export type { ResumeObjectsEducationPrimary } from './models/ResumeObjectsEducationPrimary';
export type { ResumeObjectsEmployerPaidServices } from './models/ResumeObjectsEmployerPaidServices';
export type { ResumeObjectsEmploymentFormEmploymentForm } from './models/ResumeObjectsEmploymentFormEmploymentForm';
export type { ResumeObjectsEmploymentFormEmploymentFormItem } from './models/ResumeObjectsEmploymentFormEmploymentFormItem';
export type { ResumeObjectsEmploymentFormEmploymentFormItemResponse } from './models/ResumeObjectsEmploymentFormEmploymentFormItemResponse';
export type { ResumeObjectsEmploymentFormEmploymentFormResponse } from './models/ResumeObjectsEmploymentFormEmploymentFormResponse';
export type { ResumeObjectsExperience } from './models/ResumeObjectsExperience';
export type { ResumeObjectsExperienceCreateEditResume } from './models/ResumeObjectsExperienceCreateEditResume';
export type { ResumeObjectsExperienceForOwner } from './models/ResumeObjectsExperienceForOwner';
export type { ResumeObjectsExperienceProperties } from './models/ResumeObjectsExperienceProperties';
export type { ResumeObjectsExperiencePropertiesShort } from './models/ResumeObjectsExperiencePropertiesShort';
export type { ResumeObjectsExperienceShort } from './models/ResumeObjectsExperienceShort';
export type { ResumeObjectsGender } from './models/ResumeObjectsGender';
export type { ResumeObjectsIndustry } from './models/ResumeObjectsIndustry';
export type { ResumeObjectsJobSearchStatus } from './models/ResumeObjectsJobSearchStatus';
export type { ResumeObjectsLanguage } from './models/ResumeObjectsLanguage';
export type { ResumeObjectsLastNegotiations } from './models/ResumeObjectsLastNegotiations';
export type { ResumeObjectsMetroLine } from './models/ResumeObjectsMetroLine';
export type { ResumeObjectsMetroStation } from './models/ResumeObjectsMetroStation';
export type { ResumeObjectsModerationNote } from './models/ResumeObjectsModerationNote';
export type { ResumeObjectsNegotiationsHistoryForEmployer } from './models/ResumeObjectsNegotiationsHistoryForEmployer';
export type { ResumeObjectsNegotiationsHistoryUrl } from './models/ResumeObjectsNegotiationsHistoryUrl';
export type { ResumeObjectsOneOfDownloadOrNullableObject } from './models/ResumeObjectsOneOfDownloadOrNullableObject';
export type { ResumeObjectsOneOfEducation } from './models/ResumeObjectsOneOfEducation';
export type { ResumeObjectsOneOfId } from './models/ResumeObjectsOneOfId';
export type { ResumeObjectsOneOfMetroStation } from './models/ResumeObjectsOneOfMetroStation';
export type { ResumeObjectsOneOfPhoto } from './models/ResumeObjectsOneOfPhoto';
export type { ResumeObjectsOneOfPhotoNoId } from './models/ResumeObjectsOneOfPhotoNoId';
export type { ResumeObjectsOneOfUrlOrNullableObject } from './models/ResumeObjectsOneOfUrlOrNullableObject';
export type { ResumeObjectsOwner } from './models/ResumeObjectsOwner';
export type { ResumeObjectsOwnerComments } from './models/ResumeObjectsOwnerComments';
export type { ResumeObjectsOwnerCommentsCounters } from './models/ResumeObjectsOwnerCommentsCounters';
export type { ResumeObjectsPaidServices } from './models/ResumeObjectsPaidServices';
export type { ResumeObjectsPhoto } from './models/ResumeObjectsPhoto';
export type { ResumeObjectsPhotoNoId } from './models/ResumeObjectsPhotoNoId';
export type { ResumeObjectsPhotoShort } from './models/ResumeObjectsPhotoShort';
export type { ResumeObjectsPortfolio } from './models/ResumeObjectsPortfolio';
export type { ResumeObjectsPortfolioNoId } from './models/ResumeObjectsPortfolioNoId';
export type { ResumeObjectsProgress } from './models/ResumeObjectsProgress';
export type { ResumeObjectsRecommendation } from './models/ResumeObjectsRecommendation';
export type { ResumeObjectsRelocation } from './models/ResumeObjectsRelocation';
export type { ResumeObjectsRelocationPublic } from './models/ResumeObjectsRelocationPublic';
export type { ResumeObjectsSalaryAddEdit } from './models/ResumeObjectsSalaryAddEdit';
export type { ResumeObjectsSalaryProperties } from './models/ResumeObjectsSalaryProperties';
export type { ResumeObjectsSimilarVacancies } from './models/ResumeObjectsSimilarVacancies';
export type { ResumeObjectsSite } from './models/ResumeObjectsSite';
export type { ResumeObjectsTotalExperience } from './models/ResumeObjectsTotalExperience';
export type { ResumeObjectsWorkFormatWorkFormat } from './models/ResumeObjectsWorkFormatWorkFormat';
export type { ResumeObjectsWorkFormatWorkFormatItem } from './models/ResumeObjectsWorkFormatWorkFormatItem';
export type { ResumeObjectsWorkFormatWorkFormatItemResponse } from './models/ResumeObjectsWorkFormatWorkFormatItemResponse';
export type { ResumeObjectsWorkFormatWorkFormatResponse } from './models/ResumeObjectsWorkFormatWorkFormatResponse';
export type { ResumePhoneGenerateCodeGenerateCode } from './models/ResumePhoneGenerateCodeGenerateCode';
export type { ResumePhotoPortfolio } from './models/ResumePhotoPortfolio';
export type { ResumeProfileAdditionalProperties } from './models/ResumeProfileAdditionalProperties';
export { ResumeProfileResumeProfileCreateRequestBaseBody } from './models/ResumeProfileResumeProfileCreateRequestBaseBody';
export type { ResumeProfileResumeProfileCreateRequestBody } from './models/ResumeProfileResumeProfileCreateRequestBody';
export type { ResumeProfileResumeProfileDictionariesResponse } from './models/ResumeProfileResumeProfileDictionariesResponse';
export type { ResumeProfileResumeProfileDictionaryCommunicationMethods } from './models/ResumeProfileResumeProfileDictionaryCommunicationMethods';
export type { ResumeProfileResumeProfileDictionaryTitles } from './models/ResumeProfileResumeProfileDictionaryTitles';
export type { ResumeProfileResumeProfileResponse } from './models/ResumeProfileResumeProfileResponse';
export type { ResumeProfileResumeProfileUpdateRequestBody } from './models/ResumeProfileResumeProfileUpdateRequestBody';
export type { ResumeProfileScreen } from './models/ResumeProfileScreen';
export type { ResumeReadiness } from './models/ResumeReadiness';
export type { ResumeResume } from './models/ResumeResume';
export type { ResumeResumeCommon } from './models/ResumeResumeCommon';
export type { ResumeResumeEmploymentTerms } from './models/ResumeResumeEmploymentTerms';
export type { ResumeResumeForApplicant } from './models/ResumeResumeForApplicant';
export type { ResumeResumeForEmployer } from './models/ResumeResumeForEmployer';
export type { ResumeResumeFull } from './models/ResumeResumeFull';
export type { ResumeResumeNano } from './models/ResumeResumeNano';
export type { ResumeResumeNanoWithUrl } from './models/ResumeResumeNanoWithUrl';
export type { ResumeResumeShort } from './models/ResumeResumeShort';
export type { ResumeResumeShortForOwner } from './models/ResumeResumeShortForOwner';
export type { ResumeResumeViewResponse } from './models/ResumeResumeViewResponse';
export type { ResumesAccessTypes } from './models/ResumesAccessTypes';
export type { ResumesAccessTypesItem } from './models/ResumesAccessTypesItem';
export type { ResumesAutoHideTimeOptions } from './models/ResumesAutoHideTimeOptions';
export type { ResumesByStatusCounters } from './models/ResumesByStatusCounters';
export type { ResumesByStatusResponse } from './models/ResumesByStatusResponse';
export type { ResumesCreationAvailability } from './models/ResumesCreationAvailability';
export type { ResumesGetResumeVisibilityListItem } from './models/ResumesGetResumeVisibilityListItem';
export type { ResumesGetResumeVisibilityListProperties } from './models/ResumesGetResumeVisibilityListProperties';
export type { ResumesGetResumeVisibilityListResponse } from './models/ResumesGetResumeVisibilityListResponse';
export type { ResumeShouldSendSmsContainer } from './models/ResumeShouldSendSmsContainer';
export type { ResumeShouldSendSmsPhone } from './models/ResumeShouldSendSmsPhone';
export type { ResumesMineItem } from './models/ResumesMineItem';
export type { ResumesMineItems } from './models/ResumesMineItems';
export type { ResumesMineResponse } from './models/ResumesMineResponse';
export type { ResumesNegotiationNano } from './models/ResumesNegotiationNano';
export type { ResumesPostResumeVisibilityListBody } from './models/ResumesPostResumeVisibilityListBody';
export type { ResumesResumeConditionFieldsAccessCondition } from './models/ResumesResumeConditionFieldsAccessCondition';
export type { ResumesResumeConditionFieldsAccessFields } from './models/ResumesResumeConditionFieldsAccessFields';
export type { ResumesResumeConditionFieldsContactCondition } from './models/ResumesResumeConditionFieldsContactCondition';
export type { ResumesResumeConditionFieldsContactFields } from './models/ResumesResumeConditionFieldsContactFields';
export type { ResumesResumeConditionFieldsEducationCondition } from './models/ResumesResumeConditionFieldsEducationCondition';
export type { ResumesResumeConditionFieldsEducationElementaryCondition } from './models/ResumesResumeConditionFieldsEducationElementaryCondition';
export type { ResumesResumeConditionFieldsEducationFields } from './models/ResumesResumeConditionFieldsEducationFields';
export type { ResumesResumeConditionFieldsEducationPrimaryCondition } from './models/ResumesResumeConditionFieldsEducationPrimaryCondition';
export type { ResumesResumeConditionFieldsElementaryEducationFields } from './models/ResumesResumeConditionFieldsElementaryEducationFields';
export type { ResumesResumeConditionFieldsExperienceCondition } from './models/ResumesResumeConditionFieldsExperienceCondition';
export type { ResumesResumeConditionFieldsExperienceFields } from './models/ResumesResumeConditionFieldsExperienceFields';
export type { ResumesResumeConditionFieldsLanguageCondition } from './models/ResumesResumeConditionFieldsLanguageCondition';
export type { ResumesResumeConditionFieldsLanguageFields } from './models/ResumesResumeConditionFieldsLanguageFields';
export type { ResumesResumeConditionFieldsMaxMinCount } from './models/ResumesResumeConditionFieldsMaxMinCount';
export type { ResumesResumeConditionFieldsMaxMinDate } from './models/ResumesResumeConditionFieldsMaxMinDate';
export type { ResumesResumeConditionFieldsMaxMinLength } from './models/ResumesResumeConditionFieldsMaxMinLength';
export type { ResumesResumeConditionFieldsMaxMinValue } from './models/ResumesResumeConditionFieldsMaxMinValue';
export type { ResumesResumeConditionFieldsNotIn } from './models/ResumesResumeConditionFieldsNotIn';
export type { ResumesResumeConditionFieldsPrimaryEducationFields } from './models/ResumesResumeConditionFieldsPrimaryEducationFields';
export type { ResumesResumeConditionFieldsRecommendationCondition } from './models/ResumesResumeConditionFieldsRecommendationCondition';
export type { ResumesResumeConditionFieldsRecommendationFields } from './models/ResumesResumeConditionFieldsRecommendationFields';
export type { ResumesResumeConditionFieldsRegexp } from './models/ResumesResumeConditionFieldsRegexp';
export type { ResumesResumeConditionFieldsRelocationCondition } from './models/ResumesResumeConditionFieldsRelocationCondition';
export type { ResumesResumeConditionFieldsRelocationFields } from './models/ResumesResumeConditionFieldsRelocationFields';
export type { ResumesResumeConditionFieldsRequired } from './models/ResumesResumeConditionFieldsRequired';
export type { ResumesResumeConditionFieldsRequiredCountAndLengthTitle } from './models/ResumesResumeConditionFieldsRequiredCountAndLengthTitle';
export type { ResumesResumeConditionFieldsRequiredCountWithTitle } from './models/ResumesResumeConditionFieldsRequiredCountWithTitle';
export type { ResumesResumeConditionFieldsRequiredDateWithTitle } from './models/ResumesResumeConditionFieldsRequiredDateWithTitle';
export type { ResumesResumeConditionFieldsRequiredLengthTitleNotInt } from './models/ResumesResumeConditionFieldsRequiredLengthTitleNotInt';
export type { ResumesResumeConditionFieldsRequiredLengthTitleRegexp } from './models/ResumesResumeConditionFieldsRequiredLengthTitleRegexp';
export type { ResumesResumeConditionFieldsRequiredLengthWithTitle } from './models/ResumesResumeConditionFieldsRequiredLengthWithTitle';
export type { ResumesResumeConditionFieldsRequiredValueWithTitle } from './models/ResumesResumeConditionFieldsRequiredValueWithTitle';
export type { ResumesResumeConditionFieldsRequiredWithTitle } from './models/ResumesResumeConditionFieldsRequiredWithTitle';
export type { ResumesResumeConditionFieldsSalaryCondition } from './models/ResumesResumeConditionFieldsSalaryCondition';
export type { ResumesResumeConditionFieldsSalaryFields } from './models/ResumesResumeConditionFieldsSalaryFields';
export type { ResumesResumeConditionFieldsSiteCondition } from './models/ResumesResumeConditionFieldsSiteCondition';
export type { ResumesResumeConditionFieldsSiteFields } from './models/ResumesResumeConditionFieldsSiteFields';
export type { ResumesResumeConditions } from './models/ResumesResumeConditions';
export type { ResumesResumeNegotiationsHistoryResponse } from './models/ResumesResumeNegotiationsHistoryResponse';
export type { ResumesResumeNegotiationsHistoryVacancy } from './models/ResumesResumeNegotiationsHistoryVacancy';
export type { ResumesResumeNegotiationsHistoryVacancyItem } from './models/ResumesResumeNegotiationsHistoryVacancyItem';
export type { ResumesResumeViewHistory } from './models/ResumesResumeViewHistory';
export type { ResumesResumeViewHistoryItem } from './models/ResumesResumeViewHistoryItem';
export type { ResumesResumeViewHistoryResponse } from './models/ResumesResumeViewHistoryResponse';
export type { ResumesResumeVisibilityListSearchProperties } from './models/ResumesResumeVisibilityListSearchProperties';
export type { ResumesResumeVisibilityListSearchResponse } from './models/ResumesResumeVisibilityListSearchResponse';
export type { ResumesSearchForEmployerAndApplicant } from './models/ResumesSearchForEmployerAndApplicant';
export type { ResumesSearchForResumesItem } from './models/ResumesSearchForResumesItem';
export type { ResumesSearchForResumesItems } from './models/ResumesSearchForResumesItems';
export type { ResumesSearchForResumesPrivateFields } from './models/ResumesSearchForResumesPrivateFields';
export type { ResumesSearchForResumesResponse } from './models/ResumesSearchForResumesResponse';
export type { ResumesSelectedObject } from './models/ResumesSelectedObject';
export type { ResumesSuitableResumeItem } from './models/ResumesSuitableResumeItem';
export type { ResumesSuitableResumeItems } from './models/ResumesSuitableResumeItems';
export type { ResumesSuitableResumeOverall } from './models/ResumesSuitableResumeOverall';
export type { ResumesSuitableResumesResponse } from './models/ResumesSuitableResumesResponse';
export type { ResumeStatus } from './models/ResumeStatus';
export type { ResumeStatusReadiness } from './models/ResumeStatusReadiness';
export type { ResumeViewApplicantResume } from './models/ResumeViewApplicantResume';
export { ResumeViewPlatform } from './models/ResumeViewPlatform';
export type { SalaryStatisticsEvaluationResponse } from './models/SalaryStatisticsEvaluationResponse';
export type { SalaryStatisticsIndirectCalculation } from './models/SalaryStatisticsIndirectCalculation';
export type { SalaryStatisticsMarketSalary } from './models/SalaryStatisticsMarketSalary';
export type { SalaryStatisticsResultingParameters } from './models/SalaryStatisticsResultingParameters';
export type { SavedSearchesSavedSearchItem } from './models/SavedSearchesSavedSearchItem';
export type { SavedSearchesSavedSearchItems } from './models/SavedSearchesSavedSearchItems';
export type { SavedSearchesSavedSearchResponse } from './models/SavedSearchesSavedSearchResponse';
export type { SkillVerificationsBrandingSettings } from './models/SkillVerificationsBrandingSettings';
export type { SkillVerificationsImage } from './models/SkillVerificationsImage';
export type { SkillVerificationsLevel } from './models/SkillVerificationsLevel';
export { SkillVerificationsOpenedAnswer } from './models/SkillVerificationsOpenedAnswer';
export type { SkillVerificationsResult } from './models/SkillVerificationsResult';
export type { SkillVerificationsShortMethod } from './models/SkillVerificationsShortMethod';
export type { SkillVerificationsSkill } from './models/SkillVerificationsSkill';
export { SkillVerificationsSkillCategory } from './models/SkillVerificationsSkillCategory';
export type { SkillVerificationsSkillVerification } from './models/SkillVerificationsSkillVerification';
export type { SkillVerificationsSource } from './models/SkillVerificationsSource';
export { SkillVerificationsTestResultNano } from './models/SkillVerificationsTestResultNano';
export type { SkillVerificationsTestResultTasks } from './models/SkillVerificationsTestResultTasks';
export type { SkillVerificationsTestResultWithUrl } from './models/SkillVerificationsTestResultWithUrl';
export type { SkillVerificationsValidity } from './models/SkillVerificationsValidity';
export type { SuggestsArea } from './models/SuggestsArea';
export type { SuggestsAreas } from './models/SuggestsAreas';
export type { SuggestsAreasItem } from './models/SuggestsAreasItem';
export type { SuggestsCompanies } from './models/SuggestsCompanies';
export type { SuggestsCompanyItem } from './models/SuggestsCompanyItem';
export type { SuggestsEducationalInstitutions } from './models/SuggestsEducationalInstitutions';
export type { SuggestsEmployerItem } from './models/SuggestsEmployerItem';
export { SuggestsErrors } from './models/SuggestsErrors';
export type { SuggestsFieldsOfStudy } from './models/SuggestsFieldsOfStudy';
export type { SuggestsFieldsOfStudyItem } from './models/SuggestsFieldsOfStudyItem';
export type { SuggestsLogoUrl } from './models/SuggestsLogoUrl';
export type { SuggestsPositionItem } from './models/SuggestsPositionItem';
export type { SuggestsPositions } from './models/SuggestsPositions';
export type { SuggestsProfessionalRoleItem } from './models/SuggestsProfessionalRoleItem';
export type { SuggestsProfessionalRoleItemWithName } from './models/SuggestsProfessionalRoleItemWithName';
export type { SuggestsProfessionalRoles } from './models/SuggestsProfessionalRoles';
export type { SuggestsSearchKeyword } from './models/SuggestsSearchKeyword';
export type { SuggestsSearchKeywordItem } from './models/SuggestsSearchKeywordItem';
export type { SuggestsSkillSet } from './models/SuggestsSkillSet';
export type { SuggestsSpecializationsWithName } from './models/SuggestsSpecializationsWithName';
export type { SuggestsVacancyPositionItem } from './models/SuggestsVacancyPositionItem';
export type { SuggestsVacancyPositions } from './models/SuggestsVacancyPositions';
export type { UserStatusesApplicant } from './models/UserStatusesApplicant';
export type { UserStatusesJobSearchStatus } from './models/UserStatusesJobSearchStatus';
export type { VacanciesActiveListItem } from './models/VacanciesActiveListItem';
export type { VacanciesActiveListItems } from './models/VacanciesActiveListItems';
export type { VacanciesActiveVacancyFields } from './models/VacanciesActiveVacancyFields';
export type { VacanciesAdditionalVacancyFields } from './models/VacanciesAdditionalVacancyFields';
export type { VacanciesAddress } from './models/VacanciesAddress';
export type { VacanciesArchivedVacancyList } from './models/VacanciesArchivedVacancyList';
export type { VacanciesArchivedVacancyListResponse } from './models/VacanciesArchivedVacancyListResponse';
export type { VacanciesArgumentItem } from './models/VacanciesArgumentItem';
export type { VacanciesArguments } from './models/VacanciesArguments';
export type { VacanciesAvailableVacancyTypeItem } from './models/VacanciesAvailableVacancyTypeItem';
export type { VacanciesAvailableVacancyTypeResponse } from './models/VacanciesAvailableVacancyTypeResponse';
export type { VacanciesClusterItem } from './models/VacanciesClusterItem';
export type { VacanciesClusters } from './models/VacanciesClusters';
export type { VacanciesDeletedVacancyListItems } from './models/VacanciesDeletedVacancyListItems';
export type { VacanciesDeletedVacancyListResponse } from './models/VacanciesDeletedVacancyListResponse';
export type { VacanciesEmployerPublic } from './models/VacanciesEmployerPublic';
export type { VacanciesEmployerRating } from './models/VacanciesEmployerRating';
export type { VacanciesFixes } from './models/VacanciesFixes';
export { VacanciesItemsOfClusterItem } from './models/VacanciesItemsOfClusterItem';
export type { VacanciesMatchListItem } from './models/VacanciesMatchListItem';
export type { VacanciesMatchListItems } from './models/VacanciesMatchListItems';
export type { VacanciesMatchVacancyFields } from './models/VacanciesMatchVacancyFields';
export type { VacanciesNegotiationsVacancyShort } from './models/VacanciesNegotiationsVacancyShort';
export type { VacanciesObjectsDepartment } from './models/VacanciesObjectsDepartment';
export type { VacanciesObjectsEmployer } from './models/VacanciesObjectsEmployer';
export type { VacanciesObjectsInsiderInterview } from './models/VacanciesObjectsInsiderInterview';
export type { VacanciesObjectsVacanciesEmployer } from './models/VacanciesObjectsVacanciesEmployer';
export type { VacanciesPreferredNegotiationsOrder } from './models/VacanciesPreferredNegotiationsOrder';
export type { VacanciesPreferredNegotiationsOrderRequest } from './models/VacanciesPreferredNegotiationsOrderRequest';
export type { VacanciesStandardVacancyFields } from './models/VacanciesStandardVacancyFields';
export type { VacanciesSuggests } from './models/VacanciesSuggests';
export type { VacanciesUpgradeFieldsAction } from './models/VacanciesUpgradeFieldsAction';
export type { VacanciesUpgradeFieldsBillingTypeFull } from './models/VacanciesUpgradeFieldsBillingTypeFull';
export type { VacanciesUpgradeFieldsPrice } from './models/VacanciesUpgradeFieldsPrice';
export type { VacanciesUpgradeFieldsWithoutAction } from './models/VacanciesUpgradeFieldsWithoutAction';
export type { VacanciesVacanciesBlacklisted } from './models/VacanciesVacanciesBlacklisted';
export type { VacanciesVacanciesBlacklistedItem } from './models/VacanciesVacanciesBlacklistedItem';
export type { VacanciesVacanciesBlacklistedResponse } from './models/VacanciesVacanciesBlacklistedResponse';
export type { VacanciesVacanciesFavorited } from './models/VacanciesVacanciesFavorited';
export type { VacanciesVacanciesFavoritedItem } from './models/VacanciesVacanciesFavoritedItem';
export type { VacanciesVacanciesFavoritedResponse } from './models/VacanciesVacanciesFavoritedResponse';
export type { VacanciesVacanciesItem } from './models/VacanciesVacanciesItem';
export type { VacanciesVacanciesItems } from './models/VacanciesVacanciesItems';
export type { VacanciesVacanciesResponse } from './models/VacanciesVacanciesResponse';
export type { VacanciesVacancy } from './models/VacanciesVacancy';
export type { VacanciesVacancyApplicationBody } from './models/VacanciesVacancyApplicationBody';
export type { VacanciesVacancyArchived } from './models/VacanciesVacancyArchived';
export type { VacanciesVacancyArchivedFields } from './models/VacanciesVacancyArchivedFields';
export type { VacanciesVacancyCommonFields } from './models/VacanciesVacancyCommonFields';
export type { VacanciesVacancyConditionFieldsAddressCondition } from './models/VacanciesVacancyConditionFieldsAddressCondition';
export type { VacanciesVacancyConditionFieldsAddressFields } from './models/VacanciesVacancyConditionFieldsAddressFields';
export type { VacanciesVacancyConditionFieldsContactFields } from './models/VacanciesVacancyConditionFieldsContactFields';
export type { VacanciesVacancyConditionFieldsContactsCondition } from './models/VacanciesVacancyConditionFieldsContactsCondition';
export type { VacanciesVacancyConditionFieldsMaxMinCount } from './models/VacanciesVacancyConditionFieldsMaxMinCount';
export type { VacanciesVacancyConditionFieldsMaxMinLength } from './models/VacanciesVacancyConditionFieldsMaxMinLength';
export type { VacanciesVacancyConditionFieldsMaxMinValue } from './models/VacanciesVacancyConditionFieldsMaxMinValue';
export type { VacanciesVacancyConditionFieldsNumberCondition } from './models/VacanciesVacancyConditionFieldsNumberCondition';
export type { VacanciesVacancyConditionFieldsPhoneCondition } from './models/VacanciesVacancyConditionFieldsPhoneCondition';
export type { VacanciesVacancyConditionFieldsPhoneFields } from './models/VacanciesVacancyConditionFieldsPhoneFields';
export type { VacanciesVacancyConditionFieldsRegexp } from './models/VacanciesVacancyConditionFieldsRegexp';
export type { VacanciesVacancyConditionFieldsRequired } from './models/VacanciesVacancyConditionFieldsRequired';
export type { VacanciesVacancyConditionFieldsRequiredCountWithTitle } from './models/VacanciesVacancyConditionFieldsRequiredCountWithTitle';
export type { VacanciesVacancyConditionFieldsRequiredLengthWithTitle } from './models/VacanciesVacancyConditionFieldsRequiredLengthWithTitle';
export type { VacanciesVacancyConditionFieldsRequiredValueWithTitle } from './models/VacanciesVacancyConditionFieldsRequiredValueWithTitle';
export type { VacanciesVacancyConditionFieldsRequiredWithTitle } from './models/VacanciesVacancyConditionFieldsRequiredWithTitle';
export type { VacanciesVacancyConditionFieldsResponseUrlCondition } from './models/VacanciesVacancyConditionFieldsResponseUrlCondition';
export type { VacanciesVacancyConditionFieldsSalaryCondition } from './models/VacanciesVacancyConditionFieldsSalaryCondition';
export type { VacanciesVacancyConditionFieldsSalaryFields } from './models/VacanciesVacancyConditionFieldsSalaryFields';
export type { VacanciesVacancyConditionFieldsSalaryRangeCondition } from './models/VacanciesVacancyConditionFieldsSalaryRangeCondition';
export type { VacanciesVacancyConditionFieldsSalaryRangeFields } from './models/VacanciesVacancyConditionFieldsSalaryRangeFields';
export type { VacanciesVacancyConditionFieldsTestCondition } from './models/VacanciesVacancyConditionFieldsTestCondition';
export type { VacanciesVacancyConditionFieldsTestFields } from './models/VacanciesVacancyConditionFieldsTestFields';
export type { VacanciesVacancyConditions } from './models/VacanciesVacancyConditions';
export type { VacanciesVacancyEmployer } from './models/VacanciesVacancyEmployer';
export type { VacanciesVacancyForApplicant } from './models/VacanciesVacancyForApplicant';
export type { VacanciesVacancyForManager } from './models/VacanciesVacancyForManager';
export type { VacanciesVacancyListResponse } from './models/VacanciesVacancyListResponse';
export type { VacanciesVacancyManagerFields } from './models/VacanciesVacancyManagerFields';
export type { VacanciesVacancyProlongate } from './models/VacanciesVacancyProlongate';
export type { VacanciesVacancyProlongateAvailableActions } from './models/VacanciesVacancyProlongateAvailableActions';
export type { VacanciesVacancyProlongateUnavailableActions } from './models/VacanciesVacancyProlongateUnavailableActions';
export type { VacanciesVacancyShort } from './models/VacanciesVacancyShort';
export type { VacanciesVacancyStatsItem } from './models/VacanciesVacancyStatsItem';
export type { VacanciesVacancyStatsResponse } from './models/VacanciesVacancyStatsResponse';
export type { VacanciesVacancyUpgradeListItem } from './models/VacanciesVacancyUpgradeListItem';
export type { VacanciesVacancyUpgradeListResponse } from './models/VacanciesVacancyUpgradeListResponse';
export type { VacanciesVisitorsHiddenOnPage } from './models/VacanciesVisitorsHiddenOnPage';
export type { VacanciesVisitorsResponse } from './models/VacanciesVisitorsResponse';
export type { VacanciesVisitorsVisitorItems } from './models/VacanciesVisitorsVisitorItems';
export type { VacancyAcceptHandicapped } from './models/VacancyAcceptHandicapped';
export type { VacancyAcceptIncompleteResumes } from './models/VacancyAcceptIncompleteResumes';
export type { VacancyAcceptKids } from './models/VacancyAcceptKids';
export type { VacancyAcceptTemporary } from './models/VacancyAcceptTemporary';
export type { VacancyAddress } from './models/VacancyAddress';
export type { VacancyAddressCommon } from './models/VacancyAddressCommon';
export type { VacancyAddressOutput } from './models/VacancyAddressOutput';
export type { VacancyAddressRawOutput } from './models/VacancyAddressRawOutput';
export type { VacancyAllowMessages } from './models/VacancyAllowMessages';
export type { VacancyAlternateUrl } from './models/VacancyAlternateUrl';
export type { VacancyAnyOfCreateFieldsOrWithProperties } from './models/VacancyAnyOfCreateFieldsOrWithProperties';
export type { VacancyApplyAlternateUrl } from './models/VacancyApplyAlternateUrl';
export type { VacancyApproved } from './models/VacancyApproved';
export type { VacancyArchived } from './models/VacancyArchived';
export type { VacancyArchivedAt } from './models/VacancyArchivedAt';
export type { VacancyArea } from './models/VacancyArea';
export type { VacancyAreaOutput } from './models/VacancyAreaOutput';
export { VacancyArguments } from './models/VacancyArguments';
export type { VacancyBillingType } from './models/VacancyBillingType';
export type { VacancyBillingTypeObject } from './models/VacancyBillingTypeObject';
export type { VacancyBillingTypeOutput } from './models/VacancyBillingTypeOutput';
export type { VacancyBrandedDescription } from './models/VacancyBrandedDescription';
export type { VacancyBrandedTemplate } from './models/VacancyBrandedTemplate';
export type { VacancyCanUpgradeBillingType } from './models/VacancyCanUpgradeBillingType';
export type { VacancyCode } from './models/VacancyCode';
export type { VacancyCommonFields } from './models/VacancyCommonFields';
export type { VacancyContacts } from './models/VacancyContacts';
export type { VacancyContactsOutput } from './models/VacancyContactsOutput';
export type { VacancyCounters } from './models/VacancyCounters';
export type { VacancyCountersForActive } from './models/VacancyCountersForActive';
export type { VacancyCountersForArchivedOrHidden } from './models/VacancyCountersForArchivedOrHidden';
export type { VacancyCountersOutput } from './models/VacancyCountersOutput';
export type { VacancyCreate } from './models/VacancyCreate';
export type { VacancyCreatedAt } from './models/VacancyCreatedAt';
export type { VacancyCreateFields } from './models/VacancyCreateFields';
export type { VacancyCustomEmployerName } from './models/VacancyCustomEmployerName';
export type { VacancyDepartment } from './models/VacancyDepartment';
export type { VacancyDepartmentOutput } from './models/VacancyDepartmentOutput';
export type { VacancyDescription } from './models/VacancyDescription';
export type { VacancyDescriptionAddress } from './models/VacancyDescriptionAddress';
export type { VacancyDraftAddress } from './models/VacancyDraftAddress';
export type { VacancyDraftAddressOutput } from './models/VacancyDraftAddressOutput';
export type { VacancyDraftAreas } from './models/VacancyDraftAreas';
export type { VacancyDraftAssignedManager } from './models/VacancyDraftAssignedManager';
export type { VacancyDraftAssignedManagerId } from './models/VacancyDraftAssignedManagerId';
export type { VacancyDraftAutoPublicationState } from './models/VacancyDraftAutoPublicationState';
export type { VacancyDraftBillingType } from './models/VacancyDraftBillingType';
export type { VacancyDraftBrandedTemplate } from './models/VacancyDraftBrandedTemplate';
export type { VacancyDraftCode } from './models/VacancyDraftCode';
export type { VacancyDraftContacts } from './models/VacancyDraftContacts';
export type { VacancyDraftContactsWithFullPhone } from './models/VacancyDraftContactsWithFullPhone';
export type { VacancyDraftDescription } from './models/VacancyDraftDescription';
export type { VacancyDraftDraftResponseSchema } from './models/VacancyDraftDraftResponseSchema';
export type { VacancyDraftDraftVacancyError } from './models/VacancyDraftDraftVacancyError';
export type { VacancyDraftEmployer } from './models/VacancyDraftEmployer';
export type { VacancyDraftEmployment } from './models/VacancyDraftEmployment';
export type { VacancyDraftKeySkillItem } from './models/VacancyDraftKeySkillItem';
export type { VacancyDraftKeySkills } from './models/VacancyDraftKeySkills';
export type { VacancyDraftName } from './models/VacancyDraftName';
export type { VacancyDraftPhone } from './models/VacancyDraftPhone';
export type { VacancyDraftPhoneFormatted } from './models/VacancyDraftPhoneFormatted';
export type { VacancyDraftPhoneItem } from './models/VacancyDraftPhoneItem';
export type { VacancyDraftPhoneItemWithFullPhone } from './models/VacancyDraftPhoneItemWithFullPhone';
export type { VacancyDraftProfessionalRoleItem } from './models/VacancyDraftProfessionalRoleItem';
export type { VacancyDraftProfessionalRoles } from './models/VacancyDraftProfessionalRoles';
export type { VacancyDraftPublications } from './models/VacancyDraftPublications';
export type { VacancyDraftResponseUrl } from './models/VacancyDraftResponseUrl';
export type { VacancyDraftScheduledAt } from './models/VacancyDraftScheduledAt';
export type { VacancyDraftTest } from './models/VacancyDraftTest';
export type { VacancyDraftType } from './models/VacancyDraftType';
export type { VacancyDraftVacanciesDraftResponse } from './models/VacancyDraftVacanciesDraftResponse';
export type { VacancyDraftVacancyDraftAnyOfCreateFieldsOrWithProperties } from './models/VacancyDraftVacancyDraftAnyOfCreateFieldsOrWithProperties';
export type { VacancyDraftVacancyDraftBase } from './models/VacancyDraftVacancyDraftBase';
export type { VacancyDraftVacancyDraftBodyCommon } from './models/VacancyDraftVacancyDraftBodyCommon';
export type { VacancyDraftVacancyDraftCommon } from './models/VacancyDraftVacancyDraftCommon';
export type { VacancyDraftVacancyDraftCreate } from './models/VacancyDraftVacancyDraftCreate';
export type { VacancyDraftVacancyDraftEdit } from './models/VacancyDraftVacancyDraftEdit';
export type { VacancyDraftVacancyDraftFull } from './models/VacancyDraftVacancyDraftFull';
export type { VacancyDraftVacancyDraftItem } from './models/VacancyDraftVacancyDraftItem';
export type { VacancyDraftVacancyDraftItems } from './models/VacancyDraftVacancyDraftItems';
export type { VacancyDraftVacancyDraftTypeBillingType } from './models/VacancyDraftVacancyDraftTypeBillingType';
export type { VacancyDraftVacancyProperties } from './models/VacancyDraftVacancyProperties';
export type { VacancyDraftWithZp } from './models/VacancyDraftWithZp';
export type { VacancyDriverLicenceTypeItem } from './models/VacancyDriverLicenceTypeItem';
export type { VacancyDriverLicenseTypes } from './models/VacancyDriverLicenseTypes';
export type { VacancyDuplicates } from './models/VacancyDuplicates';
export type { VacancyEdit } from './models/VacancyEdit';
export type { VacancyEditBillingType } from './models/VacancyEditBillingType';
export type { VacancyEditCommon } from './models/VacancyEditCommon';
export type { VacancyEditFields } from './models/VacancyEditFields';
export type { VacancyEditManager } from './models/VacancyEditManager';
export type { VacancyEmployerBages } from './models/VacancyEmployerBages';
export type { VacancyEmployerBlacklisted } from './models/VacancyEmployerBlacklisted';
export type { VacancyEmployment } from './models/VacancyEmployment';
export type { VacancyEmploymentForm } from './models/VacancyEmploymentForm';
export type { VacancyEmploymentFormOutput } from './models/VacancyEmploymentFormOutput';
export type { VacancyEmploymentOutput } from './models/VacancyEmploymentOutput';
export type { VacancyExperience } from './models/VacancyExperience';
export type { VacancyExperienceOutput } from './models/VacancyExperienceOutput';
export type { VacancyExpiresAt } from './models/VacancyExpiresAt';
export type { VacancyFlyInFlyOutDurationFlyInFlyOutDuration } from './models/VacancyFlyInFlyOutDurationFlyInFlyOutDuration';
export type { VacancyFlyInFlyOutDurationFlyInFlyOutDurationItem } from './models/VacancyFlyInFlyOutDurationFlyInFlyOutDurationItem';
export type { VacancyFlyInFlyOutDurationFlyInFlyOutDurationItemOutput } from './models/VacancyFlyInFlyOutDurationFlyInFlyOutDurationItemOutput';
export type { VacancyFlyInFlyOutDurationFlyInFlyOutDurationOutput } from './models/VacancyFlyInFlyOutDurationFlyInFlyOutDurationOutput';
export type { VacancyHasTest } from './models/VacancyHasTest';
export type { VacancyHasUpdates } from './models/VacancyHasUpdates';
export type { VacancyHidden } from './models/VacancyHidden';
export type { VacancyHiddenDeprecated } from './models/VacancyHiddenDeprecated';
export type { VacancyId } from './models/VacancyId';
export type { VacancyInitialCreatedAt } from './models/VacancyInitialCreatedAt';
export type { VacancyInsiderInterview } from './models/VacancyInsiderInterview';
export type { VacancyInternship } from './models/VacancyInternship';
export type { VacancyKeySkillItem } from './models/VacancyKeySkillItem';
export type { VacancyKeySkills } from './models/VacancyKeySkills';
export type { VacancyLanguage } from './models/VacancyLanguage';
export type { VacancyLanguageOutput } from './models/VacancyLanguageOutput';
export type { VacancyLanguages } from './models/VacancyLanguages';
export type { VacancyLanguagesOutput } from './models/VacancyLanguagesOutput';
export type { VacancyManager } from './models/VacancyManager';
export type { VacancyManagerOutput } from './models/VacancyManagerOutput';
export type { VacancyName } from './models/VacancyName';
export type { VacancyNegotiationActions } from './models/VacancyNegotiationActions';
export type { VacancyNegotiationSubActions } from './models/VacancyNegotiationSubActions';
export type { VacancyNightShifts } from './models/VacancyNightShifts';
export type { VacancyPhoneItem } from './models/VacancyPhoneItem';
export type { VacancyPicture } from './models/VacancyPicture';
export type { VacancyPremium } from './models/VacancyPremium';
export type { VacancyProfessionalRoleItem } from './models/VacancyProfessionalRoleItem';
export type { VacancyProfessionalRoleItemOutput } from './models/VacancyProfessionalRoleItemOutput';
export type { VacancyProfessionalRoles } from './models/VacancyProfessionalRoles';
export type { VacancyProfessionalRolesOutput } from './models/VacancyProfessionalRolesOutput';
export type { VacancyPublication } from './models/VacancyPublication';
export type { VacancyPublications } from './models/VacancyPublications';
export type { VacancyPublicationVacancyProperties } from './models/VacancyPublicationVacancyProperties';
export type { VacancyPublicPropertyTypes } from './models/VacancyPublicPropertyTypes';
export { VacancyRelationItem } from './models/VacancyRelationItem';
export type { VacancyRelations } from './models/VacancyRelations';
export type { VacancyResponseLetterRequired } from './models/VacancyResponseLetterRequired';
export type { VacancyResponseNotifications } from './models/VacancyResponseNotifications';
export type { VacancyResponseUrl } from './models/VacancyResponseUrl';
export type { VacancySalary } from './models/VacancySalary';
export type { VacancySalaryRangeSalaryRange } from './models/VacancySalaryRangeSalaryRange';
export type { VacancySalaryRangeSalaryRangeFrequency } from './models/VacancySalaryRangeSalaryRangeFrequency';
export type { VacancySalaryRangeSalaryRangeFrequencyOutput } from './models/VacancySalaryRangeSalaryRangeFrequencyOutput';
export type { VacancySalaryRangeSalaryRangeMode } from './models/VacancySalaryRangeSalaryRangeMode';
export type { VacancySalaryRangeSalaryRangeModeOutput } from './models/VacancySalaryRangeSalaryRangeModeOutput';
export type { VacancySalaryRangeSalaryRangeOutput } from './models/VacancySalaryRangeSalaryRangeOutput';
export type { VacancySchedule } from './models/VacancySchedule';
export type { VacancyScheduleOutput } from './models/VacancyScheduleOutput';
export type { VacancyShowContacts } from './models/VacancyShowContacts';
export type { VacancyShowContactsNotNull } from './models/VacancyShowContactsNotNull';
export type { VacancySnippet } from './models/VacancySnippet';
export type { VacancySortPointDistance } from './models/VacancySortPointDistance';
export type { VacancyTemplates } from './models/VacancyTemplates';
export type { VacancyType } from './models/VacancyType';
export type { VacancyTypeOutput } from './models/VacancyTypeOutput';
export type { VacancyTypes } from './models/VacancyTypes';
export type { VacancyVacancyConstructorTemplate } from './models/VacancyVacancyConstructorTemplate';
export type { VacancyVacancyProperties } from './models/VacancyVacancyProperties';
export type { VacancyVacancyPropertiesAppearance } from './models/VacancyVacancyPropertiesAppearance';
export type { VacancyVideoVacancyCoverPicture } from './models/VacancyVideoVacancyCoverPicture';
export type { VacancyVideoVacancySnippetPicture } from './models/VacancyVideoVacancySnippetPicture';
export type { VacancyVideoVacancyVideo } from './models/VacancyVideoVacancyVideo';
export type { VacancyVideoVacancyVideoVacancyItem } from './models/VacancyVideoVacancyVideoVacancyItem';
export type { VacancyWorkFormatWorkFormat } from './models/VacancyWorkFormatWorkFormat';
export type { VacancyWorkFormatWorkFormatItem } from './models/VacancyWorkFormatWorkFormatItem';
export type { VacancyWorkFormatWorkFormatItemOutput } from './models/VacancyWorkFormatWorkFormatItemOutput';
export type { VacancyWorkFormatWorkFormatOutput } from './models/VacancyWorkFormatWorkFormatOutput';
export type { VacancyWorkingDayItem } from './models/VacancyWorkingDayItem';
export type { VacancyWorkingDayItemOutput } from './models/VacancyWorkingDayItemOutput';
export type { VacancyWorkingDays } from './models/VacancyWorkingDays';
export type { VacancyWorkingDaysOutput } from './models/VacancyWorkingDaysOutput';
export type { VacancyWorkingHoursWorkingHours } from './models/VacancyWorkingHoursWorkingHours';
export type { VacancyWorkingHoursWorkingHoursItem } from './models/VacancyWorkingHoursWorkingHoursItem';
export type { VacancyWorkingHoursWorkingHoursItemOutput } from './models/VacancyWorkingHoursWorkingHoursItemOutput';
export type { VacancyWorkingHoursWorkingHoursOutput } from './models/VacancyWorkingHoursWorkingHoursOutput';
export type { VacancyWorkingTimeIntervalItem } from './models/VacancyWorkingTimeIntervalItem';
export type { VacancyWorkingTimeIntervalItemOutput } from './models/VacancyWorkingTimeIntervalItemOutput';
export type { VacancyWorkingTimeIntervals } from './models/VacancyWorkingTimeIntervals';
export type { VacancyWorkingTimeIntervalsOutput } from './models/VacancyWorkingTimeIntervalsOutput';
export type { VacancyWorkingTimeModeItem } from './models/VacancyWorkingTimeModeItem';
export type { VacancyWorkingTimeModeItemOutput } from './models/VacancyWorkingTimeModeItemOutput';
export type { VacancyWorkingTimeModes } from './models/VacancyWorkingTimeModes';
export type { VacancyWorkingTimeModesOutput } from './models/VacancyWorkingTimeModesOutput';
export type { VacancyWorkScheduleByDaysWorkScheduleByDays } from './models/VacancyWorkScheduleByDaysWorkScheduleByDays';
export type { VacancyWorkScheduleByDaysWorkScheduleByDaysItem } from './models/VacancyWorkScheduleByDaysWorkScheduleByDaysItem';
export type { VacancyWorkScheduleByDaysWorkScheduleByDaysItemOutput } from './models/VacancyWorkScheduleByDaysWorkScheduleByDaysItemOutput';
export type { VacancyWorkScheduleByDaysWorkScheduleByDaysOutput } from './models/VacancyWorkScheduleByDaysWorkScheduleByDaysOutput';
export { WebhookActionNegotiationEmployerStateChange } from './models/WebhookActionNegotiationEmployerStateChange';
export { WebhookActionNewNegotiationVacancy } from './models/WebhookActionNewNegotiationVacancy';
export { WebhookActionNewResponseOrInvitationVacancy } from './models/WebhookActionNewResponseOrInvitationVacancy';
export { WebhookActionVacancyArchivation } from './models/WebhookActionVacancyArchivation';
export { WebhookActionVacancyChange } from './models/WebhookActionVacancyChange';
export type { WebhookActionVacancyOnlyMineSettings } from './models/WebhookActionVacancyOnlyMineSettings';
export { WebhookActionVacancyProlongation } from './models/WebhookActionVacancyProlongation';
export { WebhookActionVacancyPublicationForVacancyManager } from './models/WebhookActionVacancyPublicationForVacancyManager';
export type { WebhookBadDataError } from './models/WebhookBadDataError';
export { WebhookError } from './models/WebhookError';
export type { WebhookErrors } from './models/WebhookErrors';
export type { WebhookPayloadNegotiationEmployerStateChange } from './models/WebhookPayloadNegotiationEmployerStateChange';
export type { WebhookPayloadNewNegotiationVacancy } from './models/WebhookPayloadNewNegotiationVacancy';
export type { WebhookPayloadNewResponseOrInvitationVacancy } from './models/WebhookPayloadNewResponseOrInvitationVacancy';
export type { WebhookPayloadVacancyArchivation } from './models/WebhookPayloadVacancyArchivation';
export type { WebhookPayloadVacancyChange } from './models/WebhookPayloadVacancyChange';
export type { WebhookPayloadVacancyProlongation } from './models/WebhookPayloadVacancyProlongation';
export type { WebhookPayloadVacancyPublicationForVacancyManager } from './models/WebhookPayloadVacancyPublicationForVacancyManager';
export type { WebhookSendObjectBaseUser } from './models/WebhookSendObjectBaseUser';
export type { WebhookSubscriptionCommonItem } from './models/WebhookSubscriptionCommonItem';
export type { WebhookSubscriptionCreate } from './models/WebhookSubscriptionCreate';
export type { WebhookSubscriptionItem } from './models/WebhookSubscriptionItem';
export type { WebhookSubscriptionsOutput } from './models/WebhookSubscriptionsOutput';
export type { WebhookSubscriptionUpdate } from './models/WebhookSubscriptionUpdate';

export { Service } from './services/Service';
export { ClickmeService } from './services/ClickmeService';
export { WebhookService } from './services/WebhookService';
export { WebhookApiService } from './services/WebhookApiService';
